### ISSUE TITLE
Missing prereq: Microsoft Visual C++ 2015 Redistributable Update 3 RC

### ISSUE THREAD

**Issue by gzak** [Hrnchamd/MGE-XE#14]
The readme makes no mention of needing to install [Microsoft Visual C++ 2015 Redistributable Update 3 RC](https://www.microsoft.com/en-us/download/details.aspx?id=52685), but at least on my Windows 10 PC, I had to install it in order for the game to run after installing MGE XE.

**Comment by Hrnchamd** [comment]
Sorry about the mess, I'll package these in the next release, which should be within 7 days.
