### ISSUE TITLE
Missing prereq: Microsoft Visual C++ 2010 Redistributable

### ISSUE THREAD

**Issue by dave-kennedy** [Hrnchamd/MGE-XE#16]
Similar to #14, I had to install [Microsoft Visual C++ 2010 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=5555) to run the MGE XE GUI.

**Comment by Hrnchamd** [comment]
Sorry about the mess, I'll package these in the next release, which should be within 7 days.
