### ISSUE TITLE
Source out of sync with published

### ISSUE THREAD

**Issue by NullCascade** [Hrnchamd/MGE-XE#6]
This repository is well out of sync with the latest downloads from Morrowind Nexus, obscuring the functionality of opcodes, such as xIsScripted's.

**Comment by Hrnchamd** [comment]
Pushed everything to 0.10.0-dev.

Sorry I've been gone so long without communicating.

**Comment by NullCascade** [comment]
@Hrnchamd No worries, thanks, and glad to see you around. :)

We ended up making an interface that worked with 0.10 for the [complete rewrite of MWSE](https://www.nexusmods.com/morrowind/mods/45468). Better reverse engineering done here, so I got rid of the horrible performance issues in 0.9. Would love to chat in the Morowind Modding Community Discord some time!

Thanks again for pushing!
