### ISSUE TITLE
Crash problem with pincushion

### ISSUE THREAD

**Issue by hisntfmajesty** [Hrnchamd/MGE-XE#9]
Hi Hrnchamd.
There's a big problem so when any projectile involved (me shootin' or being shot) - game crashes. And I can't even disable it as a plugin because MGE XE has it built in. Could you somehow manage it for us? I'm not the only one. 

Logs and other stuff is in pincushion thread at nexusmods.

**Comment by Hrnchamd** [comment]
This was due to a bug in MWSE, which was resolved after about 10 days. Thanks for the report.
